name = "where-durableobjects-live"
compatibility_date = "2022-11-07"
main = "src/index.ts"
workers_dev = false
minify = true

rules = [{ type = "Data", globs = ["**/*.png"], fallthrough = false }]

kv_namespaces = [
	{ binding = "KV", id = "b54534bcb1b249249357548d0fe65076", preview_id = "b54534bcb1b249249357548d0fe65076" },
]

analytics_engine_datasets = [
	{ binding = "WDL", dataset = "WhereDurableObjectsLive" }
]

[triggers]
crons = ["*/5 * * * *"]

[[durable_objects.bindings]]
name = "DO"
class_name = "DO"

[[migrations]]
tag = "2021-06-09"
new_classes = ["DO"]