name = "where-durableobjects-live"
compatibility_date = "2022-11-07"
main = "dist/index.js"

route = {pattern = "where.durableobjects.live", custom_domain = true}

[[migrations]]
tag = "2021-06-09"
new_classes = ["DurableObject"]
[[migrations]]
tag = "2022-12-11"
deleted_classes = ["DurableObject"]