// Generated by Wrangler by running `wrangler types types/env.d.ts --x-include-runtime=types/workerd.d.ts`

interface Env {
	KV: KVNamespace;
	AXIOM_TOKEN: string;
	AXIOM_ORG_ID: string;
	AXIOM_DATASET: string;
	DO: DurableObjectNamespace /* DO from where-durableobjects-live */;
	AE: AnalyticsEngineDataset;
}
